spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/auto-board?serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  session:
    store-type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}
app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: 60000 # 1분
    refresh-token-expiration-ms: 300000 # 5분
    refresh-token-expire-time-for-redis: 300 # 5분 (초 단위)
    token-prefix: "Bearer "
    header-string: "Authorization"
    issuer: ${JWT_ISSUER}