#logging.level:
#  org.hibernate.orm.jdbc.bind: trace


server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/auto-board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${GOOGLE_MAIL_ADDRESS}
    password: ${GOOGLE_APP_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        debug: false
        smtp:
          auth: true
          ssl: false
          starttls:
            enable: true
            required: true

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: 600000 # 10분
    refresh-token-expiration-ms: 3000000 # 50분
    token-prefix: "Bearer "
    header-string: "Authorization"
    issuer: ${JWT_ISSUER}
  mail:
    path: ${MAIL_PATH}
  domain: ${DOMAIN}
  openai:
    key: ${OPENAI_KEY}
  recaptcha:
    v2:
      site-key: ${RECAPTCHA_V2_SITE_KEY}
    v3:
      site-key: ${RECAPTCHA_V3_SITE_KEY}
    project-id: ${RECAPTCHA_PROJECT_ID}
  google:
    credentials:
      path: ${GOOGLE_APPLICATION_CREDENTIALS}